# Generated by Django 4.0.7 on 2023-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.CharField(choices=[('Send', 'Default'), ('Accepted', 'Accepted'), ('Refused', 'Refused')], default='Send', max_length=20)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
