# Generated by Django 4.0.7 on 2023-03-06 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers_friendships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower_friendship',
            name='users',
            field=models.ManyToManyField(related_name='followers_friendships', to=settings.AUTH_USER_MODEL),
        ),
    ]
