# Generated by Django 4.0.7 on 2023-03-08 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followers_friendships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='usuario_enviou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudar_nome1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='usuario_recebeu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudar_nome2', to=settings.AUTH_USER_MODEL),
        ),
    ]
