# Generated by Django 4.1.7 on 2023-03-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="liked",
            field=models.BooleanField(default=True),
        ),
    ]
