# Generated by Django 4.1.7 on 2023-03-14 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="liked_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
